const SUBREDDIT_SET_SUBREDDIT = 'subreddit/SUBREDDIT_SET_SUBREDDIT';
const SUBREDDIT_STARTED_FETCHING_POSTS = 'subreddit/SUBREDDIT_STARTED_FETCHING_POSTS';
const SUBREDDIT_SUCCESS_FETCHING_POSTS = 'subreddit/SUBREDDIT_SUCCESS_FETCHING_POSTS';
const SUBREDDIT_FAIL_FETCHING_POSTS = 'subreddit/SUBREDDIT_FAIL_FETCHING_POSTS';
const SUBREDDIT_RESET_POSTS = 'subreddit/SUBREDDIT_RESET_POSTS';
const SUBREDDIT_NEW_POSTS = 'subreddit/SUBREDDIT_NEW_POSTS';
const SUBREDDIT_VIEW_NEW_POSTS = 'subreddit/SUBREDDIT_VIEW_NEW_POSTS';
const SUBREDDIT_LOOK_FOR_NEW_POSTS = 'subreddit/SUBREDDIT_LOOK_FOR_NEW_POSTS';

export {
    SUBREDDIT_SET_SUBREDDIT,
    SUBREDDIT_STARTED_FETCHING_POSTS,
    SUBREDDIT_SUCCESS_FETCHING_POSTS,
    SUBREDDIT_FAIL_FETCHING_POSTS,
    SUBREDDIT_RESET_POSTS,
    SUBREDDIT_NEW_POSTS,
    SUBREDDIT_VIEW_NEW_POSTS,
    SUBREDDIT_LOOK_FOR_NEW_POSTS,
};